### ISSUE TITLE
Extract the changelog into a separate application

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-docs#10819]
### Problem Statement

We would like to separate the changelog from the docs logically to reduce the complexity of the Docs Next.js application and to be a little bit more agile with regards to using new Next.js versions and SDK features.

### Solution Brainstorm

```[tasklist]
### Tasks
- [x] Duplicate changelog into a workspace package as a separate Next.js application without depending on the docs (https://github.com/getsentry/sentry-docs/pull/10818)
- [x] Host duplicated changelog application on Vercel
- [x] Point `changelog.sentry.io` to the new changelog https://github.com/getsentry/static-sites/pull/2688
- [x] Add back proper Sentry SDK to changelog and create a project for it in Sentry https://github.com/getsentry/sentry-docs/pull/10824
- [ ] Remove old changelog code https://github.com/getsentry/sentry-docs/pull/10889
- [x] Bump Next.js & SDK to canary & latest https://github.com/getsentry/sentry-docs/pull/10876
```
