### ISSUE TITLE
[JS SDK] Update docs around `@sentry/tracing` usage

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-docs#6518]
We have removed the need to use `@sentry/tracing` - let's update the docs accordingly.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-docs/pull/6508
- [ ] https://github.com/getsentry/sentry-docs/pull/6523
- [ ] https://github.com/getsentry/sentry-docs/pull/6565
```
