### ISSUE TITLE
Improve SEO - Hide preview deployments

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-docs#6588]
We noticed that old Vercel previews are indexed by, e.g. Google.

https://sentry-docs-git-patch-1.sentry.dev

Current preview deployments contain the correct `x-robots-tag: noindex` response header, but old preview deployments do not.

Action items

```[tasklist]
### Tasks
- [x] Get rid of all stale preview deploys like https://sentry-docs-git-patch-1.sentry.dev. We'll likely do this via the Vercel API, as we have thousands of them. https://github.com/getsentry/sentry-docs/pull/6592
- [ ] Purge Google cache via https://search.google.com/search-console/, to get rid of old indexed pages. OPs ticket https://getsentry.atlassian.net/browse/OPS-3096
- [x] Add a GitHub action that deletes all preview deploys for branches that were merged/deleted.
```

**Comment by shanamatthews** [comment]
Quick update - Google was still indexing (some of?) the deleted preview deploys, Michi went into our Google Search console and started a reindex of the 404s, which should remove them from search results once the reindex finishes (should be a couple days).
