### ISSUE TITLE
Update Mobile docs for Org Auth Tokens

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-docs#7351]
Once Org Auth Tokens are GA'd, update related docs (NOTE: to be clarified if/when the new tokens can be used for purposes other than uploading source maps). These currently tell the user to create user-based auth tokens with specific scopes or otherwise vaguely mention usage of auth tokens with `sentry-cli`.

See RFC outlining how to document this: https://github.com/getsentry/rfcs/blob/main/text/0091-ci-upload-tokens.md#how-to-teach
See project Epic here: https://github.com/getsentry/team-sdks/issues/6
Also, Epic for docs changes in other places (CLI docs, sourcemaps related): https://github.com/getsentry/sentry-docs/issues/7085

```[tasklist]
### Covered in https://github.com/getsentry/sentry-docs/pull/7733
- [x] https://github.com/getsentry/sentry-docs/blob/769f4d2aaa9063705517e0b6a465c42106f44709/src/platforms/android/common/gradle.mdx
- [x] https://github.com/getsentry/sentry-docs/blob/769f4d2aaa9063705517e0b6a465c42106f44709/src/docs/clients/cocoa/dsym.mdx
- [x] https://github.com/getsentry/sentry-docs/blob/769f4d2aaa9063705517e0b6a465c42106f44709/src/platform-includes/debug-symbols-apple/_default.mdx
- [x] https://github.com/getsentry/sentry-docs/blob/f34441225301b2471658ad6888c348bee75a6f93/src/platforms/flutter/troubleshooting.mdx
- [x] https://github.com/getsentry/sentry-docs/blob/769f4d2aaa9063705517e0b6a465c42106f44709/src/platforms/react-native/manual-setup/hermes.md
- [x] https://github.com/getsentry/sentry-docs/blob/769f4d2aaa9063705517e0b6a465c42106f44709/src/platforms/unreal/debug-symbols.mdx
- [x] https://github.com/getsentry/sentry-docs/blob/769f4d2aaa9063705517e0b6a465c42106f44709/src/platforms/unity/native-support/index.mdx
```

```[tasklist]
### Tasks
- [x] https://github.com/getsentry/sentry-docs/blob/769f4d2aaa9063705517e0b6a465c42106f44709/src/platforms/flutter/upload-debug.mdx
- [x] https://github.com/getsentry/sentry-docs/blob/769f4d2aaa9063705517e0b6a465c42106f44709/src/platforms/react-native/manual-setup/codepush.mdx
- [x] Getting started docs on getsentry/sentry https://github.com/getsentry/sentry/tree/db2bae48dab8a140a6b1f72b0b80e3a0abac5e79/static/app/gettingStartedDocs
```

**Comment by kahest** [comment]
related: https://github.com/getsentry/sentry-docs/pull/7733
