### ISSUE TITLE
User Feedback * Product * Documentation -- covers both User Feedback functionalities

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#8493]
Google Drive link for internal reviews: https://docs.google.com/document/d/19zQoGVOlSLrgjf7j2SSXz-znvoLgU1dAA7VR-qGLcwM/edit

**Tasks**
- [x] Replace text in current User Feedback docs with GDoc linked above
- [x] Bring User Feedback tab placement up to be following Session Replay on the left-menu
- [x] Create a new Set Up sub-page under User Feedback [text content coming soon]
- [x] @jas-kas to upload screenshots to GDrive for download
- [x] Insert images

**Comment by jas-kas** [comment]
cc/ @JoshFerge @vivianyentran @lizokm

**Comment by bruno-garcia** [comment]
PR: https://github.com/getsentry/sentry-docs/issues/8493
