### ISSUE TITLE
SDK Documentation for New and Improved User Feedback & "Set Up" Docs Page

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#8494]
- Port the information described here to official Sentry SDK Docs: https://github.com/getsentry/sentry-javascript/tree/develop/packages/feedback#readme
- Ensure language aligns with what is described in [Product Docs](https://docs.google.com/document/d/19zQoGVOlSLrgjf7j2SSXz-znvoLgU1dAA7VR-qGLcwM/edit) for Feedback

As well as come up with a decision/game plan how to incorporate both Feedback products in one concise view.

```[tasklist]
### Tasks
- [x] Update User Feedback Docs on Browser JavaScript - [Link](https://docs.sentry.io/platforms/javascript/enriching-events/user-feedback/)
- [ ] All JavaScript frameworks
- [x] Draft the User Feedback Set Up page that shows links out to SDK instructions for both User Feedbacks on Product docs -- looks similar to [Replay Set Up page](https://docs.sentry.io/product/session-replay/getting-started/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F)
- [x] Implement the Set Up page on Product Docs
```

**Comment by jas-kas** [comment]
cc/ @billyvg @mydea
