### ISSUE TITLE
Improve Docs based on NestJS Setup

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#9177]
### Core or SDK?

Core Sentry product

### Which part? Which one?

JavaScript Source Maps

### Description

Recently 2 users in a GH issues pointed out their struggles to setup source maps upload to Sentry in their CI. There are a few points which should be covered to improve and avoid these same struggles for other users.

https://github.com/getsentry/sentry-javascript/issues/10379#issuecomment-1949953816

### Suggested Solution

```[tasklist]
### Tasks
- [ ] `@ntegral/nestjs-sentry` package is not officially supported
- [ ] if you see .ts files but no code (TypeScript trouble shooting)
- [ ] NestJS upload source maps setup guide for nestjs to include debugids v7
- [ ] NestJS SDK docs for V8 support (including source maps)
```
