### ISSUE TITLE
Streamline Setup Profiling

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-docs#9339]
### Core or SDK?

Platform/SDK

### Which part? Which one?

All where apply

### Description

Profling requires performance to work, today the docs show this in 2 different snippets. It takes up real estate and users potentially get confused or miss out on useful info on the page

### Suggested Solution

Combine the inits

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-docs/pull/9395
- [ ] https://github.com/getsentry/sentry-docs/pull/9386
- [x] Node (already follows this pattern)
- [ ] https://github.com/getsentry/sentry-docs/pull/9388
- [ ] https://github.com/getsentry/sentry-docs/pull/9394
- [x] Java - no profiling
- [ ] https://github.com/getsentry/sentry-docs/pull/9387
- [ ] https://github.com/getsentry/sentry-docs/pull/9389
- [ ] https://github.com/getsentry/sentry-docs/pull/9392
- [ ] https://github.com/getsentry/sentry-docs/pull/9393
- [x] .NET - already similar to proposed
```
